  - name: Pull an image
    containers.podman.podman_image:
      baseurl: azureregistrycasopractico2registry.azurecr.io
      name: httpd:casopractico2
      tag: casopractico2

  - name: Copying file into home
    copy:
      src: /root/ws1/index.html
      dest: /home

  - name: Re-create a redis container
    containers.podman.podman_container:
      name: sarthak
      image: httpd:casopractico2
      state: started
      detach: true
      exposed_ports:
        - 80
      ports:
        - 4444:80
      volumes: /home/:/usr/local/apache2/htdocs/