---
  - name: Deploy httpd with podman
    hosts: servers
    remote_user: azureuser
    become: true

  - tasks:
    - name: installing podman
      package:
        name: "podman"
        state: present

    - name: Installing podman
      ansible.builtin.apt:
        name: podman
        state: present

    - name: Pull apache image
      containers.podman.podman_image:
        image: azureregistrycasopractico2registry.azurecr.io
        name: httpd

    - name: Copying file into home
      copy:
        src: /root/ws1/index.html
        dest: /home

    - name: Re-create a redis container
      containers.podman.podman_container:
        name: sarthak
        image: httpd
        state: started
        detach: true
        exposed_ports:
          - 80
        ports:
          - 4444:80
        volumes: /home/:/usr/local/apache2/htdocs/